package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, June 5, 2014 1:57:25 PM ICT
*/

public interface HelloOperations 
{
  String sayHello (String param);
  void shutdown ();
} // interface HelloOperations
