# DO NOT EDIT THIS FILE!
#
# Python module _GlobalIdl__POA generated by omniidl

import omniORB
omniORB.updateModule("_GlobalIdl__POA")

# ** 1. Stub files contributing to this module
import Service_idl

# ** 2. Sub-modules

# ** 3. End
