
/**
* ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Saturday, June 7, 2014 11:26:00 AM ICT
*/

public interface ServiceOperations 
{
  void ping ();
  String hello (String param);
} // interface ServiceOperations
