
/**
* Service.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Saturday, June 7, 2014 11:26:00 AM ICT
*/

public interface Service extends ServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Service
